services:
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: dental_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backEnd:/var/www/html
      - backend_vendor:/var/www/html/vendor   # กัน vendor หาย
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  # React Frontend
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: dental_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontEnd:/app
      - /app/node_modules   # กัน node_modules conflict
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: dental_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # pgAdmin (GUI)
  pgadmin:
    image: dpage/pgadmin4
    container_name: dental_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  backend_vendor:
